[phases.setup]
nixPkgs = ["nodejs_22", "openssl"]

[phases.install]
cmds = [
  "npm ci --production=false --no-audit --no-fund",
  "npm prune --production"
]

[phases.build] 
cmds = [
  "npx prisma generate --no-engine",
  "npm run compile"
]

[start]
cmd = "npm run railway:start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"