[phases.setup]
nixPkgs = ["nodejs_22", "openssl"]

[phases.install]
cmds = ["npm ci --production=false"]

[phases.build] 
cmds = [
  "npx prisma generate",
  "npm run compile"
]

[start]
cmd = "npm run railway:start"

[variables]
NODE_ENV = "production"