[phases.setup]
nixPkgs = ["nodejs_22", "openssl"]

[phases.install]
cmds = [
  "npm ci --include=dev --no-audit --no-fund",
  "npm install prisma@^5.22.0 --save-dev --no-audit"
]

[phases.build]
cmds = [
  "npx prisma generate --no-engine",
  "npm run compile"
]

[start]
cmd = "npm run railway:start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
PRISMA_CLI_BINARY_TARGETS = "debian-openssl-3.0.x"s