[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run build && npm run setup:database && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"