[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm install --no-audit --no-fund && npm run build && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 30
healthcheckInterval = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"