[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run railway:start"
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[networking]
externalPort = 4000

[scaling]
maxReplicas = 1
minReplicas = 1